### ISSUE TITLE
How to pre-select a certain item?

### ISSUE THREAD

**Issue by vtomic85** [yangyxd/flutter_picker#170]
Hi,

I am using this picker with two options in the list (let's call them "A" and "B"). Initially, the default option is "A". When I switch to "B", I would like the picker to "remember" it somehow, so when I open it again, I would like the option "B" to be preselected. Is this possible?
Thanks.

**Comment by kekag** [comment]
The `selecteds` attribute on the `Picker` can control the default value. Just provide the indices of whichever options you want the default to be, e.g.:

```
selecteds: <int>[
  1, // the second option will be selected
]
```



Otherwise, if you're using a `NumberPickerAdapter`, the `NumberPickerColumn` object has an `initValue` attribute which provides this same functionality.

**Comment by justintoth** [comment]
I can confirm that passing the selected index in with the "selecteds" property works. This should probably be closed.
